---
title: "Практическое задание 3"
output:
  pdf_document: default
  html_document:
    df_print: paged
header-includes:
- \usepackage[russian]{babel}
- \usepackage{hyperref}
- \hypersetup{ colorlinks = true, urlcolor = blue}
---

*Все файлы для задания можно найти в материалах к уроку. В заданиях 2-4 используйте только средства библиотеки dplyr (tidyverse).*

1. Загрузите данные из файла `Ratings.csv` в датафрейм `rate`. Файл содержит экспертные оценки в 10-балльной шкале, поставленные адвокатами судьям Верховного суда США.
```{r}
rate <- read.csv("3.5_Data/data/Ratings.csv")
```


2. Сохраните в переменную good строки, которые соответствуют судьям, получившим выше 5 баллов за готовность к судебному процессу (`PREP`) и при этом выше 8 баллов за спонтанные решения (`DECI`).

3. Сохраните в переменную bad.small строки соответствующие судьям, получившим не более 5.5 за знание законов (`FAMI`) и при этом менее 6 баллов за управление потоком дел (`CFMG`). Сделайте так, чтобы в полученном датафрейме были только столбцы с оценками готовности к судебному процессу (`PREP`), управление потоком дел (`CFMG`), знание законов и физическую активность (`PHYS`).  

4. Добавьте в датафрейм `rate` столбец со средним баллом за внятные устные и письменные постановления (среднее столбцов `ORAL` и `WRIT`).
