---
title: "Практическое задание 2"
output:
  pdf_document: default
  html_document:
    df_print: paged
header-includes:
- \usepackage[russian]{babel}
- \usepackage{hyperref}
- \hypersetup{ colorlinks = true, urlcolor = blue}
---

*Все файлы для задания можно найти в материалах к уроку.*

1. Загрузите данные из файла `mtcars.csv` и сохраните в переменную `dat.cars`. Файл содержит характеристики автомобилей разных марок.

2. Выведите на экран число строк и число столбцов в датафрейме.

    *Подсказка:* воспользуйтесь функцией `dim()`.

3. Проверьте, что все столбцы датафрейма имеют корректный тип (например, что числа не считались как строки).

4. Выведите на экран описательные статистики для показателя «число лошадиных сил» (столбец `hp`). 

     * Чему равно медианное значение? 
     * Чему равны минимальное и максимальное значение?
     * Что больше: среднее число лошадиных сил или медианное?

    *Подсказка:* функцию, которую мы применяли для вывода описательных статистик всех показателей таблицы можно применить и к отдельному столбцу.

5. Добавьте в датафрейм столбец `wt_kg` с весом автомобиля в килограммах (сейчас они в тысячах английских фунтов, один фунт примерно равен 0.45 килограмма).

6. Выведите на экран в отдельном окне следующие строки:

    * соответствующие автомобилям с ручной коробкой передач (значение 1 в `am`);
    * соответствующие автомобилям с более, чем 4 передними двигателями (столбец `gear`) и мощностью менее 120 лошадиных сил (столбец `hp`).

    Сколько автомобилей удовлетворяют условиям выше? Выведите ответ на экран, воспользовавшись функцией `nrow()` для определения числа строк в датафрейме.
