---
title: "Практическое задание 4"
output:
  pdf_document: default
  html_document:
    df_print: paged
header-includes:
- \usepackage[russian]{babel}
- \usepackage{hyperref}
- \hypersetup{ colorlinks = true, urlcolor = blue}
---

1. Напишите функцию `bmi()`, которая принимает на вход рост пользователя в сантиметрах и вес в килограммах, а возвращает индекс массы тела, округленный до целого значения. Индекс массы тела считается так:

```
BMI = m / h**2,
```
где m – масса тела в килограммах, h – рост в метрах.

Обратите внимание, в формуле для BMI рост должен указываться в метрах, не сантиметрах.

2. Напишите функцию, которая принимает на вход имя пользователя, и если оно совпадает Вашим, выводит на экран “[Name], welcome to R! I missed you”, где вместо “[Name]” подставляется имя, а если не совпадает, то выводит на экран “Sorry, R is not available now”. 

Подразумевается, что R знает Ваше имя – оно сохранено в отдельную переменную. 

3. Напишите функцию, которая принимает на вход таблицу с числами (датафрейм), и возвращает два значения: максимальная сумма чисел по строкам и максимальная сумма чисел по столбцам.

*Подсказка:* для нахождения максимального значения в векторе с суммами по строкам или столбцам можно воспользоваться функцией `max()`. 

Пример:

```{r}
s <- c(8, 6, 5, 1, 3)
max(s)
```
