---
title: "Module 7 Homework"
output: html_notebook
---

### Задача 3
В файле experiment.csv сохранены результаты эксперимента, описанного в задаче 1. Данные представляют собой последовательности из 0 и 1, где 1 соответствует людям, которые захотели выбрать кофе с измененным дизайном эткетки, а 0 - людям, которые не захотели.

#### Описание данных:

test: результаты по тестовой группе (людям предлагали кофе с новым дизайном этикетки); control: контрольная группа (людям предлагали кофе со старым дизайном этикетки).

1. Загрузите в R данные из файла experiment.csv с помощью функции read.csv().
2. Постройте в R 90%-ный доверительный интервал для доли людей, которые захотели купить кофе, в тестовой группе. Проинтерпретируйте полученный доверительный интервал. В решении приведите используемый код, границы доверительного интервала и текст с интерпретацией.
3. Постройте в R 90%-ный доверительный интервал для доли людей, которые захотели купить кофе, в контрольной группе. Проинтерпретируйте полученный доверительный интервал. В решении приведите используемый код, границы доверительного интервала и текст с интерпретацией.
4. Сравните полученные доверительные интервалы для тестовой и контрольной группы. Можно ли на основании полученных результатов сделать определенный вывод о том, что новый дизайн этикетки лучше (привлекает больше потенциальных покупателей)? Приведите ваши выводы и объяснения.
5. Выполните пункты 1-3 в Python. Изменились ли ваши выводы относительно полезности нового дизайна этикетки? Приведите код, результаты и текст с выводами. 

```{r}
df <- read.csv("experiment.csv")
library(DescTools)
BinomCI(sum(df$test), length(df$test), conf.level = 0.9)
```
Построен 90%-ный доверительный интервал тестовой группы.
Нижняя граница: 0.5511289
Верхняя граница: 0.6024556
С 90%-ной вероятностью доля людей, решивших приобрести кофе в новой упаковке попадет в интервал (0.5511289, 0.6024556).

